# build environment
FROM node:9.9.0 as builder
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
RUN npm install
RUN npm install react-scripts -g
COPY . /usr/src/app
ARG REACT_APP_BASE_ENDPOINT
RUN echo $REACT_APP_BASE_ENDPOINT
RUN REACT_APP_BASE_ENDPOINT=$REACT_APP_BASE_ENDPOINT npm run build

# production environment
FROM nginx:1.13.9-alpine
RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]